//! Runtime drift detection for repository-managed runtime surfaces.

use anyhow::{Context, Result};
use nettoolskit_core::runtime_execution::{
    resolve_runtime_execution_context, RuntimeExecutionContext,
};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

use crate::{error::RuntimeDoctorCommandError, invoke_runtime_bootstrap, RuntimeBootstrapRequest};

/// Request payload for `doctor`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RuntimeDoctorRequest {
    /// Optional explicit repository root.
    pub repo_root: Option<PathBuf>,
    /// Optional explicit GitHub runtime target path.
    pub target_github_path: Option<PathBuf>,
    /// Optional explicit Codex runtime target path.
    pub target_codex_path: Option<PathBuf>,
    /// Optional explicit picker-visible agent skills path.
    pub target_agents_skills_path: Option<PathBuf>,
    /// Optional explicit Copilot native skills path.
    pub target_copilot_skills_path: Option<PathBuf>,
    /// Optional explicit runtime profile name.
    pub runtime_profile: Option<String>,
    /// Optional explicit fallback runtime profile name.
    ///
    /// When omitted, `doctor` follows the PowerShell contract and falls back to
    /// `all`.
    pub fallback_runtime_profile: Option<String>,
    /// Treat extra runtime files as drift failures.
    pub strict_extras: bool,
    /// Run runtime synchronization when drift is detected, then re-check.
    pub sync_on_drift: bool,
}

/// Drift status summary for a `doctor` invocation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuntimeDoctorStatus {
    /// No drift or unmanaged extras were detected.
    Clean,
    /// Runtime is aligned but contains unmanaged extra files.
    CleanWithExtras,
    /// Missing or drifted files remain, or extras were treated as failures.
    Detected,
}

/// One mapping report generated by `doctor`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeDoctorMappingReport {
    /// Human-readable mapping name.
    pub name: String,
    /// Canonical source root.
    pub source_path: PathBuf,
    /// Canonical target root.
    pub target_path: PathBuf,
    /// Number of filtered source files considered by the mapping.
    pub source_count: usize,
    /// Number of filtered target files considered by the mapping.
    pub target_count: usize,
    /// Source-managed files missing from the runtime target.
    pub missing_in_runtime: Vec<String>,
    /// Runtime files not tracked by the source mapping.
    pub extra_in_runtime: Vec<String>,
    /// Files present on both sides whose content hashes differ.
    pub drifted_files: Vec<String>,
    /// Whether the mapping is healthy under the current strictness mode.
    pub is_healthy: bool,
}

/// Result payload for `doctor`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeDoctorResult {
    /// Resolved repository root.
    pub repo_root: PathBuf,
    /// Effective runtime profile name.
    pub runtime_profile_name: String,
    /// Runtime profile catalog used to resolve the profile.
    pub runtime_profile_catalog_path: PathBuf,
    /// Drift reports produced by the command.
    pub reports: Vec<RuntimeDoctorMappingReport>,
    /// Whether any mapping is unhealthy.
    pub has_drift: bool,
    /// Whether any runtime extras were detected.
    pub has_extras: bool,
    /// Overall drift status.
    pub status: RuntimeDoctorStatus,
    /// Whether drift remediation sync was attempted.
    pub sync_attempted: bool,
    /// Whether remediation sync cleared all drift findings on the second pass.
    pub sync_resolved_drift: bool,
    /// Number of mappings audited for the active runtime profile.
    pub mappings_checked: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct DoctorMapping {
    name: &'static str,
    source_path: PathBuf,
    target_path: PathBuf,
    include_prefixes: Vec<String>,
    ignore_source_prefixes: Vec<String>,
    ignore_extra_prefixes: Vec<String>,
}

/// Diagnose drift between repository-managed sources and local runtime
/// projections.
///
/// # Errors
///
/// Returns [`RuntimeDoctorCommandError`] when workspace resolution, runtime
/// execution context resolution, or drift inventory construction fails.
pub fn invoke_runtime_doctor(
    request: &RuntimeDoctorRequest,
) -> Result<RuntimeDoctorResult, RuntimeDoctorCommandError> {
    let current_dir =
        env::current_dir().map_err(|source| RuntimeDoctorCommandError::ResolveWorkspaceRoot {
            source: source.into(),
        })?;
    let fallback_profile = request.fallback_runtime_profile.as_deref().or(Some("all"));
    let context = resolve_runtime_execution_context(
        request.repo_root.as_deref(),
        request.runtime_profile.as_deref(),
        fallback_profile,
        request.target_github_path.as_deref(),
        request.target_codex_path.as_deref(),
        request.target_agents_skills_path.as_deref(),
        request.target_copilot_skills_path.as_deref(),
        None,
        &current_dir,
    )
    .map_err(|source| RuntimeDoctorCommandError::ResolveExecutionContext { source })?;

    let mut reports = invoke_doctor(&context, request.strict_extras)
        .map_err(|source| RuntimeDoctorCommandError::BuildReport { source })?;
    let (mut has_drift, mut has_extras, mut status) = summarize_doctor_reports(&reports);
    let mut sync_attempted = false;
    let mut sync_resolved_drift = false;

    if has_drift && request.sync_on_drift {
        sync_attempted = true;
        invoke_runtime_bootstrap(&RuntimeBootstrapRequest {
            repo_root: Some(context.resolved_repo_root.clone()),
            target_github_path: Some(context.targets.github_runtime_root.clone()),
            target_codex_path: Some(context.targets.codex_runtime_root.clone()),
            target_agents_skills_path: Some(context.targets.agents_skills_root.clone()),
            target_copilot_skills_path: Some(context.targets.copilot_skills_root.clone()),
            runtime_profile: Some(context.runtime_profile.name.clone()),
            fallback_runtime_profile: request.fallback_runtime_profile.clone(),
            mirror: false,
            apply_mcp_config: false,
            backup_config: false,
        })
        .map_err(|source| RuntimeDoctorCommandError::SynchronizeRuntime {
            source: source.into(),
        })?;

        reports = invoke_doctor(&context, request.strict_extras)
            .map_err(|source| RuntimeDoctorCommandError::BuildReport { source })?;
        (has_drift, has_extras, status) = summarize_doctor_reports(&reports);
        sync_resolved_drift = !has_drift;
    }

    Ok(RuntimeDoctorResult {
        repo_root: context.resolved_repo_root,
        runtime_profile_name: context.runtime_profile.name,
        runtime_profile_catalog_path: context.runtime_profile.catalog_path,
        mappings_checked: reports.len(),
        reports,
        has_drift,
        has_extras,
        status,
        sync_attempted,
        sync_resolved_drift,
    })
}

fn summarize_doctor_reports(
    reports: &[RuntimeDoctorMappingReport],
) -> (bool, bool, RuntimeDoctorStatus) {
    let has_drift = reports.iter().any(|report| !report.is_healthy);
    let has_extras = reports
        .iter()
        .any(|report| !report.extra_in_runtime.is_empty());
    let status = if has_drift {
        RuntimeDoctorStatus::Detected
    } else if has_extras {
        RuntimeDoctorStatus::CleanWithExtras
    } else {
        RuntimeDoctorStatus::Clean
    };

    (has_drift, has_extras, status)
}

fn invoke_doctor(
    context: &RuntimeExecutionContext,
    strict_extras: bool,
) -> Result<Vec<RuntimeDoctorMappingReport>> {
    let mappings = doctor_mappings(context)?;
    let mut reports = mappings
        .into_iter()
        .map(|mapping| compare_mapping(&mapping, strict_extras))
        .collect::<Result<Vec<_>>>()?;

    if context.runtime_profile.enable_codex_runtime {
        reports.push(test_codex_skill_duplicate_state(
            &context.sources.codex_skills_root,
            &context.targets.codex_runtime_root.join("skills"),
        )?);
    }

    Ok(reports)
}

fn doctor_mappings(context: &RuntimeExecutionContext) -> Result<Vec<DoctorMapping>> {
    let mut mappings = Vec::new();

    if context.runtime_profile.enable_github_runtime {
        mappings.extend([
            DoctorMapping {
                name: ".github -> runtime",
                source_path: context.sources.github_root.clone(),
                target_path: context.targets.github_runtime_root.clone(),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: vec!["scripts".to_string()],
            },
            DoctorMapping {
                name: "scripts -> runtime .github/scripts",
                source_path: context.sources.scripts_root.clone(),
                target_path: context.targets.github_runtime_root.join("scripts"),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: Vec::new(),
            },
            DoctorMapping {
                name: "legacy starter cleanup -> runtime .github/skills and .copilot/skills",
                source_path: context.sources.github_skills_root.clone(),
                target_path: context.targets.copilot_skills_root.clone(),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: Vec::new(),
            },
        ]);
    }

    if context.runtime_profile.enable_codex_runtime {
        let managed_skill_prefixes = managed_skill_name_list(&context.sources.codex_skills_root)?;
        let unmanaged_agent_prefixes = unmanaged_directory_prefixes(
            &context.targets.agents_skills_root,
            &managed_skill_prefixes,
        )?;
        mappings.extend([
            DoctorMapping {
                name: ".codex/skills -> runtime .agents/skills",
                source_path: context.sources.codex_skills_root.clone(),
                target_path: context.targets.agents_skills_root.clone(),
                include_prefixes: managed_skill_prefixes,
                ignore_source_prefixes: vec!["README.md".to_string()],
                ignore_extra_prefixes: unmanaged_agent_prefixes,
            },
            DoctorMapping {
                name: ".codex/mcp -> runtime",
                source_path: context.sources.codex_mcp_root.clone(),
                target_path: context.targets.codex_runtime_root.join("shared-mcp"),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: Vec::new(),
            },
            DoctorMapping {
                name: ".codex/scripts (root tools) -> runtime",
                source_path: context.sources.codex_scripts_root.clone(),
                target_path: context.targets.codex_runtime_root.join("shared-scripts"),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: vec![
                    "common".to_string(),
                    "security".to_string(),
                    "maintenance".to_string(),
                ],
            },
            DoctorMapping {
                name: "scripts/common -> runtime",
                source_path: context.sources.common_scripts_root.clone(),
                target_path: context
                    .targets
                    .codex_runtime_root
                    .join("shared-scripts")
                    .join("common"),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: Vec::new(),
            },
            DoctorMapping {
                name: "scripts/security -> runtime",
                source_path: context.sources.security_scripts_root.clone(),
                target_path: context
                    .targets
                    .codex_runtime_root
                    .join("shared-scripts")
                    .join("security"),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: Vec::new(),
            },
            DoctorMapping {
                name: "scripts/maintenance -> runtime",
                source_path: context.sources.maintenance_scripts_root.clone(),
                target_path: context
                    .targets
                    .codex_runtime_root
                    .join("shared-scripts")
                    .join("maintenance"),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: Vec::new(),
            },
            DoctorMapping {
                name: ".codex/orchestration -> runtime",
                source_path: context.sources.codex_orchestration_root.clone(),
                target_path: context
                    .targets
                    .codex_runtime_root
                    .join("shared-orchestration"),
                include_prefixes: Vec::new(),
                ignore_source_prefixes: Vec::new(),
                ignore_extra_prefixes: Vec::new(),
            },
        ]);
    }

    Ok(mappings)
}

fn compare_mapping(
    mapping: &DoctorMapping,
    strict_extras: bool,
) -> Result<RuntimeDoctorMappingReport> {
    let source_inventory = select_inventory_entries(
        &file_inventory(&mapping.source_path)?,
        &mapping.include_prefixes,
        &mapping.ignore_source_prefixes,
    );
    let target_inventory = select_inventory_entries(
        &file_inventory(&mapping.target_path)?,
        &mapping.include_prefixes,
        &[],
    );

    let source_lookup = lowercase_inventory(&source_inventory);
    let target_lookup = lowercase_inventory(&target_inventory);

    let missing_in_runtime = source_inventory
        .keys()
        .filter(|key| !target_lookup.contains_key(&key.to_ascii_lowercase()))
        .cloned()
        .collect::<Vec<_>>();

    let extra_in_runtime = target_inventory
        .keys()
        .filter(|key| !source_lookup.contains_key(&key.to_ascii_lowercase()))
        .filter(|key| !path_prefix_matches(key, &mapping.ignore_extra_prefixes))
        .cloned()
        .collect::<Vec<_>>();

    let drifted_files = source_inventory
        .iter()
        .filter_map(|(key, source_hash)| {
            target_lookup
                .get(&key.to_ascii_lowercase())
                .and_then(|(target_key, target_hash)| {
                    (source_hash != target_hash).then(|| target_key.clone())
                })
        })
        .collect::<Vec<_>>();

    Ok(RuntimeDoctorMappingReport {
        name: mapping.name.to_string(),
        source_path: mapping.source_path.clone(),
        target_path: mapping.target_path.clone(),
        source_count: source_inventory.len(),
        target_count: target_inventory.len(),
        missing_in_runtime: missing_in_runtime.clone(),
        extra_in_runtime: extra_in_runtime.clone(),
        drifted_files: drifted_files.clone(),
        is_healthy: missing_in_runtime.is_empty()
            && drifted_files.is_empty()
            && (!strict_extras || extra_in_runtime.is_empty()),
    })
}

fn test_codex_skill_duplicate_state(
    managed_skill_root: &Path,
    codex_skills_root: &Path,
) -> Result<RuntimeDoctorMappingReport> {
    let managed_skill_names = managed_skill_name_list(managed_skill_root)?;
    let duplicates = managed_skill_names
        .iter()
        .filter(|skill_name| codex_skills_root.join(skill_name).exists())
        .cloned()
        .collect::<Vec<_>>();
    let target_count = if codex_skills_root.is_dir() {
        fs::read_dir(codex_skills_root)
            .with_context(|| format!("failed to enumerate '{}'", codex_skills_root.display()))?
            .filter_map(std::result::Result::ok)
            .count()
    } else {
        0
    };

    Ok(RuntimeDoctorMappingReport {
        name: "repo-managed skill duplicates in runtime .codex/skills".to_string(),
        source_path: managed_skill_root.to_path_buf(),
        target_path: codex_skills_root.to_path_buf(),
        source_count: managed_skill_names.len(),
        target_count,
        missing_in_runtime: Vec::new(),
        extra_in_runtime: duplicates.clone(),
        drifted_files: Vec::new(),
        is_healthy: duplicates.is_empty(),
    })
}

fn managed_skill_name_list(skill_root: &Path) -> Result<Vec<String>> {
    if !skill_root.is_dir() {
        return Ok(Vec::new());
    }

    let mut skill_names = fs::read_dir(skill_root)
        .with_context(|| format!("failed to enumerate '{}'", skill_root.display()))?
        .filter_map(std::result::Result::ok)
        .filter_map(|entry| {
            entry
                .file_type()
                .ok()
                .filter(|file_type| file_type.is_dir())
                .and_then(|_| entry.file_name().to_str().map(ToOwned::to_owned))
        })
        .collect::<Vec<_>>();
    skill_names.sort();
    skill_names.dedup();
    Ok(skill_names)
}

fn unmanaged_directory_prefixes(root: &Path, managed_prefixes: &[String]) -> Result<Vec<String>> {
    if !root.is_dir() {
        return Ok(Vec::new());
    }

    let mut prefixes = fs::read_dir(root)
        .with_context(|| format!("failed to enumerate '{}'", root.display()))?
        .filter_map(std::result::Result::ok)
        .filter_map(|entry| {
            entry
                .file_type()
                .ok()
                .filter(|file_type| file_type.is_dir())
                .and_then(|_| entry.file_name().to_str().map(ToOwned::to_owned))
        })
        .filter(|name| !managed_prefixes.contains(name))
        .collect::<Vec<_>>();
    prefixes.sort();
    Ok(prefixes)
}

fn file_inventory(root_path: &Path) -> Result<BTreeMap<String, String>> {
    let mut inventory = BTreeMap::new();
    if !root_path.exists() {
        return Ok(inventory);
    }

    for entry in WalkDir::new(root_path) {
        let entry = entry.with_context(|| format!("failed to walk '{}'", root_path.display()))?;
        if !entry.file_type().is_file() {
            continue;
        }

        let relative_path = entry
            .path()
            .strip_prefix(root_path)
            .with_context(|| {
                format!(
                    "failed to compute relative path for '{}' from '{}'",
                    entry.path().display(),
                    root_path.display()
                )
            })?
            .to_string_lossy()
            .replace('\\', "/");
        let bytes = fs::read(entry.path())
            .with_context(|| format!("failed to read '{}'", entry.path().display()))?;
        let digest = Sha256::digest(bytes);
        inventory.insert(relative_path, format!("{digest:X}"));
    }

    Ok(inventory)
}

fn select_inventory_entries(
    inventory: &BTreeMap<String, String>,
    include_prefixes: &[String],
    ignore_prefixes: &[String],
) -> BTreeMap<String, String> {
    inventory
        .iter()
        .filter(|(path, _)| {
            include_prefixes.is_empty() || path_prefix_matches(path, include_prefixes)
        })
        .filter(|(path, _)| !path_prefix_matches(path, ignore_prefixes))
        .map(|(path, hash)| (path.clone(), hash.clone()))
        .collect()
}

fn lowercase_inventory(inventory: &BTreeMap<String, String>) -> BTreeMap<String, (String, String)> {
    inventory
        .iter()
        .map(|(path, hash)| (path.to_ascii_lowercase(), (path.clone(), hash.clone())))
        .collect()
}

fn path_prefix_matches(relative_path: &str, prefixes: &[String]) -> bool {
    let normalized_path = relative_path.replace('\\', "/");
    prefixes
        .iter()
        .filter_map(|prefix| {
            let normalized = prefix.replace('\\', "/");
            let trimmed = normalized.trim_matches('/').to_string();
            (!trimmed.is_empty()).then_some(trimmed)
        })
        .any(|prefix| {
            normalized_path.eq_ignore_ascii_case(&prefix)
                || normalized_path
                    .to_ascii_lowercase()
                    .starts_with(&format!("{}/", prefix.to_ascii_lowercase()))
        })
}
